name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: liyuanhan007
        password: dckr_pat_qA3c9fswEfytcEG8P-6-1ea2V6g
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag liyuanhan007/vsftpd-alpine:latest
    - name: Docker image push
      run: docker push liyuanhan007/vsftpd-alpine:latest
